[colors.bright]
black = "#CFC1BA"
blue = "#1D5573"
cyan = "#2B747C"
green = "#3F5A22"
magenta = "#7B3B70"
red = "#94253E"
white = "#4F5E68"
yellow = "#803D1C"

[colors.cursor]
cursor = "#2C363C"
text = "#F0EDEC"

[colors.normal]
black = "#F0EDEC"
blue = "#286486"
cyan = "#3B8992"
green = "#4F6C31"
magenta = "#88507D"
red = "#A8334C"
white = "#2C363C"
yellow = "#944927"

[colors.primary]
background = "#F0EDEC"
foreground = "#2C363C"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 13

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Period"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Period"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = false
opacity = 0.95

[window.padding]
x = 7
y = 7
